### ISSUE TITLE
using_angular_mocks.js is not working with jsonHal

### ISSUE THREAD

**Issue by Chrisposure** [traverson/traverson-angular#36] opened 2018-01-15 15:27 UTC
Hi Basti,

could you please take a look into your test code **using_angular_mocks.js**. I don't get it to work with .jsonHal(). The promise callbacks are never called...

Thank you,
Christian

**Comment by Chrisposure** [comment] 2018-01-16 10:34
Hi Basti,

here ist my test case. I always got an unsatisfied get request for the second call:
`
it('should read a HAL resource', function() {

      var apiRootResponse = {
        "_links": {
          "bills": {
            "href": "http://localhost:9014/api/v1/bills{?page,size,sort}",
            "templated": true
          }
        }
      };

      var billsResponse = {
        "_embedded": {
          "bills": [{
            "receiptNr": 750000002,
            "status": "ABORTIVE",
            "billingDate": "2017-11-09T23:00:00.000+0000",
            "dispatchDate": null,
            "createdBy": "file_upload",
            "createdDate": "2018-01-15T11:59:10.162+0000",
            "modifiedBy": "admin",
            "lastModifiedDate": "2018-01-15T12:10:00.059+0000",
            "_links": {
              "self": {
                "href": "http://localhost:9014/api/v1/bills/1"
              }
            }
          }, {
            "receiptNr": 900000002,
            "status": "ABORTIVE",
            "billingDate": "2017-11-09T23:00:00.000+0000",
            "dispatchDate": null,
            "createdBy": "file_upload",
            "createdDate": "2018-01-15T11:59:10.635+0000",
            "modifiedBy": "admin",
            "lastModifiedDate": "2018-01-15T12:10:00.059+0000",
            "_links": {
              "self": {
                "href": "http://localhost:9014/api/v1/bills/2"
              }
            }
          }, {
            "receiptNr": 790000002,
            "status": "ABORTIVE",
            "billingDate": "2017-11-09T23:00:00.000+0000",
            "dispatchDate": null,
            "createdBy": "file_upload",
            "createdDate": "2018-01-15T11:59:11.039+0000",
            "modifiedBy": "admin",
            "lastModifiedDate": "2018-01-15T12:10:00.075+0000",
            "_links": {
              "self": {
                "href": "http://localhost:9014/api/v1/bills/3"
              }
            }
          }]
        },
        "_links": {
          "self": {
            "href": "http://localhost:9014/api/v1/bills{&sort}",
            "templated": true
          }
        }
      };

      $httpBackend.expectGET('api/v1', undefined, {
        'Accept': TraversonJsonHalAdapter.mediaType
      }).respond(200, JSON.stringify(apiRootResponse), {
        'Content-Type': TraversonJsonHalAdapter.mediaType
      });

      $httpBackend.expectGET('http://localhost:9014/api/v1/bills', undefined, {
        'Accept': TraversonJsonHalAdapter.mediaType
      }).respond(200, JSON.stringify(
        billsResponse), {
        'Content-Type': TraversonJsonHalAdapter.mediaType
      });

// Traverson call is encapsulated by the restClientService  (it is translated to 
//  traverson.from(BasePath).useAngularHttp().jsonHal().
// newRequest().follow(linkRelations).withTemplateParameters( templateParameters).get().result;
      var promise = restClientService.read(['bills', 'bills[$all]']);
      promise.then(function success(response) {
        console.log(arguments);

      }, function err(error) {
        console.error(arguments);
        fail('read request should not fail' + JSON.stringify(error));
      });

      $httpBackend.flush();
      $timeout(function() {
        $httpBackend.flush();
      });
      $timeout.flush();
    });
`

**Comment by basti1302** [comment] 2018-01-30 06:57
Hi,

this seems to be an incomplete snippet. Please submit the full test file, so that I can immediately reproduce the problem without guessing the missing parts. Then I might be inclined to take a look.

Also, what do you mean by "could you please take a look into your test code using_angular_mocks.js." Why should I take a look into it? It is running fine. :-)

Lastly, the tests are not part of the public API, so I can only offer limited support on them. 
Closing for now, feel free to reopen, when you attach a [Short, Self Contained, Compilable Example](http://sscce.org/).

**Closed by basti1302** 2018-01-30 06:57 UTC
